### ISSUE TITLE
finished core of the assignment 

### ISSUE THREAD

**Issue by aperium** [aperium/ga2#1]
Hi @jelmerp

Thanks for the fun assignment. I made some stupid mistakes along the way and learned from them.

**Comment by jelmerp** [comment]
Well done!

| Section   | Description                           | Max. points | Your points | Remarks    |
| --------- | ------------------------------------- | :---------: | :---------: | ---------- |
| 1.        | Initialize Git repo w/ README         |     0.5     |     0.5     |
| 2.        | Copy FASTQ files                      |     0.5     |     0.5     |
| 3.        | Ignore FASTQ files in .gitignore      |     0.5     |     0.5     | See below. |
| 4.        | Create a Conda environment            |      1      |      1      |
| 5.        | Export Conda environment YAML         |     0.5     |     0.5     |
| 6.        | _shebang_ and SLURM directives        |     0.5     |     0.5     |
| 7.        | `set` settings and load Conda env     |     0.5     |     0.5     |
| 8.        | Four arguments for the script         |      1      |      1      |
| 9.        | Compute reverse complement            |      0      |      0      |
| 10.       | Get R2 FASTQ file name                |     0.5     |     0.5     |
| 11.       | Get output file names                 |      1      |      1      |
| 12.       | Create output dir if needed           |     0.5     |     0.5     |
| 13.       | Call Cutadapt                         |      0      |      0      |
| 14.       | Submit SLURM job - repeat until works |      2      |      2      |
| 15.       | Cleanup and commit check              |     0.5     |     0.5     |
| 16.       | Push repo online and start issue      |     0.5     |     0.5     |
|           | **Assignment late**                   |             |   **-1**    |
| **TOTAL** |                                       |   **10**    |    **9**    |

For step 3, you have a line with just `.fastq` in your `.gitignore` which will only match a file with the exact name `.fastq`. And since you also have a line with `*.fastq`, the `.fastq` line will not do anything at all.

I did not subtract points for this, though -- it is barely worth that anyway, and also, my instructions were confusing here: if you had already committed the FASTQ files at step 2, as implicitly instructed, they would remain in the repo because `.gitignore` does not work "retroactively" / delete files that are present. Most students therefore had these FASTQ files in their repo and I assume this may have also confused you.

**Comment by aperium** [comment]
Thanks!
